### PR TITLE
allow specifying index type for CachedExtensionHomomorphism

### PR DESCRIPTION
**Pull request by kalmarek**
Problem:
No way to create `CachedExtensionHomomorphism` with specified index type. For large basis this could lead to hard to fix errors (without diving deep into the package).

Before:
```julia
julia> ehom = SymbolicWedderburn.CachedExtensionHomomorphism(G,action,words)
ERROR: "index type UInt16 is to small for basis of length 88572"
Stacktrace:
 [1] Basis
   @ ~/.julia/packages/StarAlgebras/0yFWh/src/bases.jl:9 [inlined]
 [2] ExtensionHomomorphism
   @ ~/.julia/dev/SymbolicWedderburn/src/ext_homomorphisms.jl:57 [inlined]
 [3] SymbolicWedderburn.CachedExtensionHomomorphism(::Type{Int16}, G::PermGroup{Perm{UInt16}, …}, action::OnLetters, basis::Vector{Word{Symbol}}; precompute::Bool)
   @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/ext_homomorphisms.jl:87
 [4] SymbolicWedderburn.CachedExtensionHomomorphism(::Type{Int16}, G::PermGroup{Perm{UInt16}, …}, action::OnLetters, basis::Vector{Word{Symbol}})
   @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/ext_homomorphisms.jl:80
 [5] top-level scope
   @ REPL[42]:1
```

After:
```julia
julia> ehom = SymbolicWedderburn.CachedExtensionHomomorphism(Int32, G,action,words);

julia> SW.induce(ehom, one(G))
()

julia> typeof(ans)
Perm{Int32}

```

CC: @laurentbartholdi

### CODE REVIEW

**Comment by laurentbartholdi** [comment]
This works now fine for "CachedExtensionHomomorphism".

However, the all-in-one "sabasis = SymbolicWedderburn.symmetry_adapted_basis(UInt32, G, action, words)" does not work -- I suspect actually the "UInt32" is interpreted as a type for the scalars in the resulting basis, not a type for the permutations.

In fact, I can't see any situation in which UInt16 is better than UInt32 for permutations. If they fit in a UInt16, then unless you're programming a Commodore 64 you'll have plenty of free memory so UInt32 would also work. On the other hand there may be cases in which the user would like UInt64, but then leave it to them.

**Comment by kalmarek** [comment]
@laurentbartholdi The proper solution should be that the index type is inferrable from `G` and `action`.

**Comment by kalmarek** [comment]
Well, that's exactly what we need to do then ;)

@laurentbartholdi it's not only about the memory, but rather lookup (=hashing speed) in the dictionary

**Review by laurentbartholdi — APPROVED** [review]
The tests are broken, but the code itself seems very good to me.

**Pull request merged**
