### PR TITLE
Increasing code coverage

### PR DESCRIPTION
**Pull request by tweisser**
TODO
- [x] fix Alt(4) example
- [ ] add tests for characters.jl

### CODE REVIEW

**Comment by kalmarek** [comment]
that is a nice trick with `using Pkg; Pkg.add(...)` ;-)

**Comment by kalmarek** [comment]
but I don't think there's much to test with characters for now; I'll add more tests for GFs though

**Comment by tweisser** [comment]
Does the FiniteFields implementation work for q = p^n?

**Comment by kalmarek** [comment]
> Does the FiniteFields implementation work for q = p^n?

No, but I didn't want to add `isprime` check to the constructor, it's too heavy.

**Comment by tweisser** [comment]
No, I think we can merge now and do the characters.jl after we have added cyclotomics.

**Pull request merged**
