### PR TITLE
Allow more groups than permutation group

### PR DESCRIPTION
**Pull request by blegat**
See https://github.com/jump-dev/SumOfSquares.jl/pull/185

### CODE REVIEW

**Comment by blegat** [comment]
I have revised it and split it into three independent PRs.

**Comment by kalmarek** [comment]
cool, thanks. I'm a bit overwhelmed right now with the Group interface

**Comment by kalmarek** [comment]
and my life situation, in general ;/

**Comment by blegat** [comment]
No problem ;)

**Comment by blegat** [comment]
Superseeded by https://github.com/kalmarek/SymbolicWedderburn.jl/pull/32

**Pull request closed without merging**
