### PR TITLE
update to PermutationGroups-0.4

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by kalmarek** [comment]
@blegat this shouldn't break SumOfSquares, if it does you should depend on `PermutationGroups.jl` explicitly

**Comment by kalmarek** [comment]
I've run this
```
using Pkg
using Revise
using SumOfSquares
Pkg.activate("docs")
using PermutationGroups

include("src/tutorials/Symmetry/cyclic.jl")
include("src/tutorials/Symmetry/dihedral.jl")
include("src/tutorials/Symmetry/even_reduction.jl")
include("src/tutorials/Symmetry/permutation_symmetry.jl")
```
with devd `SymbolicWedderburn.jl` and I got a few failures; I'm not sure they're related to changes here:

```
julia> include("docs/src/tutorials/Symmetry/cyclic.jl")
ERROR: LoadError: Constraints of type MathOptInterface.VectorAffineFunction{ComplexF64}-in-SumOfSquares.SOSPolynomialSet{FullSpace, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{NonnegPolyInnerCone{MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}, MonomialBasis, SumOfSquares.Certificate.NewtonFilter{SumOfSquares.Certificate.NewtonDegreeBounds{Tuple{}}}}, CyclicGroup, Action{Variable{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}} are not supported by the solver.

If you expected the solver to support your problem, you may have an error in your formulation. Otherwise, consider using a different solver.

The list of available solvers, along with the problem types they support, is available at https://jump.dev/JuMP.jl/stable/installation/#Supported-solvers.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] _moi_add_constraint(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{CSDP.Optimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, f::MathOptInterface.VectorAffineFunction{ComplexF64}, s::SumOfSquares.SOSPolynomialSet{FullSpace, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{NonnegPolyInnerCone{MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}, MonomialBasis, SumOfSquares.Certificate.NewtonFilter{SumOfSquares.Certificate.NewtonDegreeBounds{Tuple{}}}}, CyclicGroup, Action{Variable{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}})
   @ JuMP ~/.julia/packages/JuMP/jZvaU/src/constraints.jl:679
 [3] add_constraint(model::Model, con::VectorConstraint{GenericAffExpr{ComplexF64, VariableRef}, SumOfSquares.SOSPolynomialSet{FullSpace, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{NonnegPolyInnerCone{MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}, MonomialBasis, SumOfSquares.Certificate.NewtonFilter{SumOfSquares.Certificate.NewtonDegreeBounds{Tuple{}}}}, CyclicGroup, Action{Variable{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}}, PolyJuMP.PolynomialShape{Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}, name::String)
   @ JuMP ~/.julia/packages/JuMP/jZvaU/src/constraints.jl:706
 [4] add_constraint(model::Model, con::BridgeableConstraint{VectorConstraint{GenericAffExpr{ComplexF64, VariableRef}, SumOfSquares.SOSPolynomialSet{FullSpace, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{NonnegPolyInnerCone{MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}, MonomialBasis, SumOfSquares.Certificate.NewtonFilter{SumOfSquares.Certificate.NewtonDegreeBounds{Tuple{}}}}, CyclicGroup, Action{Variable{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}}, PolyJuMP.PolynomialShape{Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}, UnionAll, Float64}, name::String)
   @ JuMP ~/.julia/packages/JuMP/jZvaU/src/constraints.jl:533
 [5] add_constraint(model::Model, con::BridgeableConstraint{BridgeableConstraint{VectorConstraint{GenericAffExpr{ComplexF64, VariableRef}, SumOfSquares.SOSPolynomialSet{FullSpace, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{NonnegPolyInnerCone{MathOptInterface.HermitianPositiveSemidefiniteConeTriangle}, MonomialBasis, SumOfSquares.Certificate.NewtonFilter{SumOfSquares.Certificate.NewtonDegreeBounds{Tuple{}}}}, CyclicGroup, Action{Variable{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}}, PolyJuMP.PolynomialShape{Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}}, UnionAll, Float64}, UnionAll, Float64}, name::String)
   @ JuMP ~/.julia/packages/JuMP/jZvaU/src/constraints.jl:533
 [6] macro expansion
   @ ~/.julia/packages/JuMP/jZvaU/src/macros.jl:1072 [inlined]
 [7] top-level scope
   @ ~/.julia/dev/SumOfSquares/docs/src/tutorials/Symmetry/cyclic.jl:147
 [8] include(fname::String)
   @ Base.MainInclude ./client.jl:478
 [9] top-level scope
   @ REPL[6]:1
in expression starting at /home/kalmar/.julia/dev/SumOfSquares/docs/src/tutorials/Symmetry/cyclic.jl:147
```

```
julia> include("docs/src/tutorials/Symmetry/dihedral.jl")
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
SymbolicWedderburn.action(DihedralAction(), g, poly) = 1 - y² - x² - y⁴ + 3x²y² - x⁴ + y⁶ - x²y⁴ - x⁴y² + x⁶
CSDP 6.2.0
Iter:  0 Ap: 0.00e+00 Pobj:  0.0000000e+00 Ad: 0.00e+00 Dobj:  0.0000000e+00 
Iter:  1 Ap: 7.31e-01 Pobj: -5.9540730e+00 Ad: 8.42e-01 Dobj:  3.0671681e-01 
Iter:  2 Ap: 8.67e-01 Pobj: -1.6845198e+01 Ad: 8.68e-01 Dobj:  7.9208056e+00 
Iter:  3 Ap: 8.41e-01 Pobj: -6.5167134e+00 Ad: 6.91e-01 Dobj:  4.6340995e+00 
Iter:  4 Ap: 7.89e-01 Pobj: -3.0718725e+00 Ad: 8.67e-01 Dobj:  8.7844427e-01 
Iter:  5 Ap: 8.59e-01 Pobj: -1.8420731e+00 Ad: 8.47e-01 Dobj: -3.3091073e-01 
Iter:  6 Ap: 7.40e-01 Pobj: -1.2180543e+00 Ad: 8.00e-01 Dobj: -6.8726801e-01 
Iter:  7 Ap: 8.82e-01 Pobj: -1.0523759e+00 Ad: 6.48e-01 Dobj: -8.1732010e-01 
Iter:  8 Ap: 6.75e-01 Pobj: -9.8406190e-01 Ad: 7.70e-01 Dobj: -8.8525802e-01 
Iter:  9 Ap: 8.70e-01 Pobj: -9.5552035e-01 Ad: 7.26e-01 Dobj: -9.1517421e-01 
Iter: 10 Ap: 1.00e+00 Pobj: -9.2933412e-01 Ad: 8.92e-01 Dobj: -9.2629286e-01 
Iter: 11 Ap: 8.61e-01 Pobj: -9.2914325e-01 Ad: 9.11e-01 Dobj: -9.3036068e-01 
Iter: 12 Ap: 1.00e+00 Pobj: -9.2898054e-01 Ad: 1.00e+00 Dobj: -9.3115787e-01 
Iter: 13 Ap: 7.19e-01 Pobj: -9.2961473e-01 Ad: 5.76e-01 Dobj: -9.3155210e-01 
Iter: 14 Ap: 1.00e+00 Pobj: -9.2967228e-01 Ad: 3.55e-01 Dobj: -9.3180771e-01 
Iter: 15 Ap: 4.26e-01 Pobj: -9.3065963e-01 Ad: 1.00e+00 Dobj: -9.3175040e-01 
Iter: 16 Ap: 1.00e+00 Pobj: -9.3042297e-01 Ad: 1.00e+00 Dobj: -9.3211446e-01 
Iter: 17 Ap: 5.06e-01 Pobj: -9.3106101e-01 Ad: 6.25e-01 Dobj: -9.3240546e-01 
Iter: 18 Ap: 7.18e-01 Pobj: -9.3146998e-01 Ad: 4.44e-01 Dobj: -9.3257853e-01 
Iter: 19 Ap: 1.00e+00 Pobj: -9.3128112e-01 Ad: 3.48e-01 Dobj: -9.3271014e-01 
Iter: 20 Ap: 4.85e-01 Pobj: -9.3206037e-01 Ad: 1.00e+00 Dobj: -9.3257740e-01 
Iter: 21 Ap: 1.00e+00 Pobj: -9.3178232e-01 Ad: 1.00e+00 Dobj: -9.3276737e-01 
Iter: 22 Ap: 7.26e-01 Pobj: -9.3197870e-01 Ad: 7.39e-01 Dobj: -9.3290369e-01 
Iter: 23 Ap: 4.04e-01 Pobj: -9.3208730e-01 Ad: 4.06e-01 Dobj: -9.3295435e-01 
Iter: 24 Ap: 1.00e+00 Pobj: -9.3209505e-01 Ad: 1.00e+00 Dobj: -9.3296372e-01 
Iter: 25 Ap: 7.03e-01 Pobj: -9.3212572e-01 Ad: 7.08e-01 Dobj: -9.3298098e-01 
Iter: 26 Ap: 9.98e-01 Pobj: -9.3212657e-01 Ad: 9.95e-01 Dobj: -9.3298156e-01 
Stuck at edge of primal feasibility, giving up. 
Partial Success: SDP solved with reduced accuracy
Primal objective value: -9.3212665e-01 
Dual objective value: -9.3298157e-01 
Relative primal infeasibility: 3.98e-08 
Relative dual infeasibility: 3.29e-10 
Real Relative Gap: -2.98e-04 
XZ Relative Gap: 2.05e-09 
DIMACS error measures: 5.22e-08 0.00e+00 8.68e-10 0.00e+00 -2.98e-04 2.05e-09
value(t) = -0.9321266534577521
Test Failed at /home/kalmar/.julia/dev/SumOfSquares/docs/src/tutorials/Symmetry/dihedral.jl:152
  Expression: (g[1]).basis.polynomials == [y ^ 3, x ^ 2 * y, -y]
   Evaluated: Polynomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}, Float64}[y³, x²y, y] == Term{Int64, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}[y³, x²y, -y]

ERROR: LoadError: There was an error during testing
in expression starting at /home/kalmar/.julia/dev/SumOfSquares/docs/src/tutorials/Symmetry/dihedral.jl:183
```

**Comment by blegat** [comment]
Should be fixed by https://github.com/jump-dev/JuMP.jl/pull/3437 which is in JuMP v1.14 whose just been released so try again and it should work :)

**Comment by kalmarek** [comment]
> Should be fixed by [jump-dev/JuMP.jl#3437](https://github.com/jump-dev/JuMP.jl/pull/3437) which is in JuMP v1.14 whose just been released so try again and it should work :)

ok, the first problem is fixed by JuMP-1.14; The second persists:
```julia
Test Failed at /home/kalmar/.julia/dev/SumOfSquares/docs/src/tutorials/Symmetry/dihedral.jl:152
  Expression: (g[1]).basis.polynomials == [y ^ 3, x ^ 2 * y, -y]
   Evaluated: Polynomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}, Float64}[y³, x²y, y] == Term{Int64, Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}[y³, x²y, -y]

ERROR: LoadError: There was an error during testing
in expression starting at /home/kalmar/.julia/dev/SumOfSquares/docs/src/tutorials/Symmetry/dihedral.jl:183
```

**Comment by blegat** [comment]
We can change the test, whether it is `-y` or `y`, it does not matter

**Comment by kalmarek** [comment]
I didn't notice the `-` sign, I thought it's about the types :D

**Pull request merged**
